sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
script: npm t
